/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 27 04:12:07 GMT 2018
 */

package com.uepb.tcc.tennis.evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import com.uepb.tcc.tennis.TennisGame1;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TennisGame1_ESTest extends TennisGame1_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TennisGame1 tennisGame1_0 = new TennisGame1("jogador1", "jogador1");
      tennisGame1_0.ganhouPonto("jogador1");
      tennisGame1_0.ganhouPonto("jogador1");
      tennisGame1_0.ganhouPonto("jogador1");
      tennisGame1_0.ganhouPonto("Quarenta-Love");
      String string0 = tennisGame1_0.getPontuacao();
      //  // Unstable assertion: assertEquals("Vitoria para jogador2", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TennisGame1 tennisGame1_0 = new TennisGame1("", "");
      tennisGame1_0.ganhouPonto("jogador1");
      tennisGame1_0.ganhouPonto("");
      tennisGame1_0.ganhouPonto("");
      tennisGame1_0.ganhouPonto("Quinze-All");
      tennisGame1_0.ganhouPonto("");
      String string0 = tennisGame1_0.getPontuacao();
      assertEquals("Vitoria para jogador2", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TennisGame1 tennisGame1_0 = new TennisGame1("jogador1", "jogador1");
      tennisGame1_0.ganhouPonto("jogador1");
      tennisGame1_0.ganhouPonto("jogador1");
      tennisGame1_0.ganhouPonto("jogador1");
      String string0 = tennisGame1_0.getPontuacao();
      //  // Unstable assertion: assertEquals("Love-Quarenta", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TennisGame1 tennisGame1_0 = new TennisGame1("", "");
      tennisGame1_0.ganhouPonto("jogador1");
      tennisGame1_0.ganhouPonto("");
      String string0 = tennisGame1_0.getPontuacao();
      //  // Unstable assertion: assertEquals("Love-Trinta", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TennisGame1 tennisGame1_0 = new TennisGame1("", "");
      String string0 = tennisGame1_0.getPontuacao();
      assertEquals("Love-All", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TennisGame1 tennisGame1_0 = new TennisGame1("jogador1", "jogador1");
      tennisGame1_0.ganhouPonto("jogador1");
      String string0 = tennisGame1_0.getPontuacao();
      //  // Unstable assertion: assertEquals("Love-Quinze", string0);
  }
}
